<a href="https://colab.research.google.com/github/ABajad/ANN-from-scratch/blob/master/Layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Output from a neuron :**
> Output from neuron = (input to neuron)X(Weight of neuron) + Bias of neuron


**Output from all neuron :**


> Output from neuron1 = (input to neuron1)X(Weight of neuron1) + Bias of neuron1

> Output from neuron2 = (input to neuron2)X(Weight of neuron2) + Bias of neuron2

> Output from neuron3 = (input to neuron3)X(Weight of neuron3) + Bias of neuron3





**Output from Layer:** [Output from neuron1, Output from neuron1, Output from neuron1]


# From Scratch


Input to Layer

In [0]:
inputs = [1.0, 2.0, 3.0, 2.5]             #Input to neural Network

Setting Weights and biases of one Layer with 3 neurons

In [0]:
weights1 = [0.2, 0.8, -0.5, 1.0]          #Weighhts of neuron 1
weights2 = [0.5, -0.91, 0.26, -0.5]       #Weights of neuron 2
weights3 = [-0.26, -0.27, 0.17, 0.87]     #Weights of neuron 3

bias1 = 2.0                               #Bias of neuron 1
bias2 = 3.0                               #Bias of neuron 2
bias3 = 0.5                               #bias of neuron 3

Running Layer

In [13]:
output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,    #Neuron 1
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,    #Neuron 2
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]    #Neuron 3
print(output)                                                                                                       #Printing output

[4.8, 1.21, 2.385]


# Using Numpy Library

In [0]:
import numpy as np                                             #Importing Library

TRANSPOSE

In [15]:
A = [[6,7],
     [8,9]]
B = [[1,2],
     [3,4],
     [5,6]]

print(np.array(B))                 #This prints Matrix B
print(np.array(B).shape)           #This prints the shape of Matrix B, which is (2,3)

#Dot product is possible When a=c in shape (axb).(cxd)
#Dot Product A.B is not possible since Dimensions are (2x2).(3x2)
#To solve this problem we take transpose of B
#Now Dot Product is possible since shape is (2x2)(2x3)        

print(np.array(B).T)                                            #Transpose of B
print(np.array(B).T.shape)                                      #Shape of Transpose of B
print(np.dot(A,np.array(B).T))                                  #Dot Product of A and B'

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 3 5]
 [2 4 6]]
(2, 3)
[[20 46 72]
 [26 60 94]]


In [0]:
inputs = [1.0, 2.0, 3.0, 2.5]                                   #inputs to nn
weights = [[0.2, 0.8, -0.5, 1],                                 #Weights of neural-1
           [0.5, -0.91, 0.26, -0.5],                            #Weights of neural-2
           [-0.26, -0.27, 0.17, 0.87]]                          #Weights of neural-3
biases = [2.0, 3.0, 0.5]                                        #[Bias of neural-1, Bias of neural-2, Bias of neural-3]

In [17]:
layer_outputs = np.dot(inputs, np.array(weights).T) + biases    #Dot Product of inputs and weights'
print(layer_outputs)                                            #Printing Output

[4.8   1.21  2.385]


# Batch Processing From Scratch

In [0]:
inputs = [[1.0, 2.0, 3.0, 2.5],   
         [2.0, 5.0, -1.0, 2.0],                                 #shape of the input batch array is (3, 4)
         [-1.5, 2.7, 3.3, -0.8]]

In [29]:
biases[0]

2.0

In [0]:
weights = [[0.2, 0.8, -0.5, 1],                                 #Weights of neural-1
           [0.5, -0.91, 0.26, -0.5],                            #Weights of neural-2
           [-0.26, -0.27, 0.17, 0.87]]                          #Weights of neural-3
biases = [2.0, 3.0, 0.5]                                        #[Bias of neural-1, Bias of neural-2, Bias of neural-3]

In [36]:
output = [[inputs[0][0]*weights1[0] + inputs[0][1]*weights1[1] + inputs[0][2]*weights1[2] + inputs[0][3]*weights1[3] + biases[0],    
          inputs[0][0]*weights2[0] + inputs[0][1]*weights2[1] + inputs[0][2]*weights2[2] + inputs[0][3]*weights2[3] + biases[1],    
          inputs[0][0]*weights3[0] + inputs[0][1]*weights3[1] + inputs[0][2]*weights3[2] + inputs[0][3]*weights3[3] + biases[2]],

          [inputs[1][0]*weights1[0] + inputs[1][1]*weights1[1] + inputs[1][2]*weights1[2] + inputs[1][3]*weights1[3] + biases[0],    
          inputs[1][0]*weights2[0] + inputs[1][1]*weights2[1] + inputs[1][2]*weights2[2] + inputs[1][3]*weights2[3] + biases[1],    
          inputs[1][0]*weights3[0] + inputs[1][1]*weights3[1] + inputs[1][2]*weights3[2] + inputs[1][3]*weights3[3] + biases[2]],
          
          [inputs[2][0]*weights1[0] + inputs[2][1]*weights1[1] + inputs[2][2]*weights1[2] + inputs[2][3]*weights1[3] + biases[0],    
          inputs[2][0]*weights2[0] + inputs[2][1]*weights2[1] + inputs[2][2]*weights2[2] + inputs[2][3]*weights2[3] + biases[1],    
          inputs[2][0]*weights3[0] + inputs[2][1]*weights3[1] + inputs[2][2]*weights3[2] + inputs[2][3]*weights3[3] + biases[2]]]    
print(output)                                                    #Printing output, long float output is floating point problem

[[4.8, 1.21, 2.385], [8.9, -1.8099999999999996, 0.19999999999999996], [1.4100000000000001, 1.0509999999999997, 0.025999999999999912]]


# Batch processing Using Numpy Library

using multiple inputs at once

In [0]:
inputs = [[1.0, 2.0, 3.0, 2.5],   
         [2.0, 5.0, -1.0, 2.0],                                 #shape of the input batch array is (3, 4)
         [-1.5, 2.7, 3.3, -0.8]]

In [0]:
weights = [[0.2, 0.8, -0.5, 1],                                 #Weights of neural-1
           [0.5, -0.91, 0.26, -0.5],                            #Weights of neural-2
           [-0.26, -0.27, 0.17, 0.87]]                          #Weights of neural-3
biases = [2.0, 3.0, 0.5]                                        #[Bias of neural-1, Bias of neural-2, Bias of neural-3]

In [21]:
layer_outputs = np.dot(inputs, np.array(weights).T) + biases    #Dot Product of inputs and weights'
print(layer_outputs)                                            #Printing Output

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
